# Generated by Django 4.2.7 on 2023-11-29 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apprentis',
            fields=[
                ('IdApprentis', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=20)),
                ('Prenom', models.CharField(max_length=50)),
                ('DateNaiss', models.DateField()),
                ('Sexe', models.CharField(max_length=10)),
                ('CIN', models.CharField(max_length=50)),
                ('Adresse', models.CharField(max_length=20)),
                ('Tel', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('IdModule', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NomModule', models.CharField(max_length=20)),
                ('Droit', models.DecimalField(decimal_places=2, max_digits=64)),
            ],
        ),
        migrations.CreateModel(
            name='Bachelier',
            fields=[
                ('apprentis_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='information.apprentis')),
                ('DateSession', models.DateField()),
                ('Serie', models.CharField(max_length=3)),
                ('CentreExamen', models.CharField(max_length=20)),
                ('Mention', models.CharField(max_length=20)),
                ('NumInscriBacc', models.IntegerField()),
            ],
            bases=('information.apprentis',),
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('apprentis_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='information.apprentis')),
                ('LieuTravail', models.CharField(max_length=20)),
                ('Fonction', models.CharField(max_length=20)),
            ],
            bases=('information.apprentis',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('NotePratique', models.DecimalField(decimal_places=2, max_digits=60)),
                ('NoteTheorique', models.DecimalField(decimal_places=2, max_digits=60)),
                ('IdApprentis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.apprentis')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('NumInscri', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateInscri', models.DateField()),
                ('TotalDroit', models.DecimalField(decimal_places=2, max_digits=64)),
                ('IdApprentis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.apprentis')),
                ('IdModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.module')),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('IdFormater', models.IntegerField(primary_key=True, serialize=False)),
                ('NomFormater', models.CharField(max_length=20)),
                ('EmailFormater', models.CharField(max_length=50)),
                ('TelFormater', models.CharField(max_length=20)),
                ('Certification', models.TextField()),
                ('IdModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.module')),
            ],
        ),
    ]
