# Generated by Django 5.0 on 2023-12-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='IdModule',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
